################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SX_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
DDF/EDROOMModel/UAHMarsDrone/ClasesActor \
DDF/uah_mars_drone_freertos_hito1/asw/components/ccdronemng/src \
DDF/uah_mars_drone_freertos_hito1/asw/components/uahmarsdrone/src \
DDF/uah_mars_drone_freertos_hito1/asw/dataclasses/CDEvAction/src \
DDF/uah_mars_drone_freertos_hito1/asw/dataclasses/CDTCHandler/src \
DDF/uah_mars_drone_freertos_hito1/asw/dataclasses/CDTCMemDescriptor/src \
DDF/uah_mars_drone_freertos_hito1/asw/edroom_glue/src \
DDF/uah_mars_drone_freertos_hito1/llsw/device_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/emu_adc_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/emu_hw_timecode_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/emu_sc_channel_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/emu_watchdog_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/freertos_osswr/Source \
DDF/uah_mars_drone_freertos_hito1/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DDF/uah_mars_drone_freertos_hito1/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DDF/uah_mars_drone_freertos_hito1/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DDF/uah_mars_drone_freertos_hito1/llsw/obt_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/tc_queue_drv/src \
DDF/uah_mars_drone_freertos_hito1/llsw/tc_rate_ctrl/src \
DDF/uah_mars_drone_freertos_hito1/llsw/tmtc_dyn_mem/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/ccsds_pus/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/crc/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/edroomsl/edroombp/src/freertossapi \
DDF/uah_mars_drone_freertos_hito1/service_libraries/edroomsl/edroomsl/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/edroomsl/edroomsl_types/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/pus_service01/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/pus_service129/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/pus_sys_data_pool/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/pus_tc_handler/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/pus_tm_handler/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/pus_services/src \
DDF/uah_mars_drone_freertos_hito1/service_libraries/serialize/src \
DDF/uah_mars_drone_freertos_hito1 \
DJF/ITs/IT_ASW_CCDrineMng/ClasesActor \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/asw/dataclasses/CDEvAction/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/asw/dataclasses/CDTCHandler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/asw/dataclasses/CDTCMemDescriptor/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/asw/edroom_glue/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/device_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_adc_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_display_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_gss/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_hw_timecode_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_sc_channel_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_uah_drone_cinematics/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/emu_watchdog_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/freertos_osswr/Source \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/obt_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/tc_queue_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/tc_rate_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/llsw/tmtc_dyn_mem/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/ccsds_pus/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/crc/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/drone_flight_pid_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/edroomsl/edroombp/src/freertossapi \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/edroomsl/edroomsl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/edroomsl/edroomsl_types/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/emu_tc_programming/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_service01/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_service05/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_service129/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_sys_data_pool/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_tc_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/pus_tm_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/pus_services/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug/service_libraries/serialize/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/Debug \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/components/ccbkgtcexec/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/components/ccdronemng/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/components/cchk_fdirmng/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/components/cctcmanager/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/components/uah_asw/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/dataclasses/CDEvAction/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/dataclasses/CDTCHandler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/dataclasses/CDTCMemDescriptor/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/asw/edroom_glue/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/device_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_adc_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_display_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_gss/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_hw_timecode_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_sc_channel_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_uah_drone_cinematics/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/emu_watchdog_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/freertos_osswr/Source \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/obt_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/tc_queue_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/tc_rate_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/llsw/tmtc_dyn_mem/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/ccsds_pus/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/crc/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/drone_flight_pid_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/edroomsl/edroombp/src/freertossapi \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/edroomsl/edroomsl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/edroomsl/edroomsl_types/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/emu_tc_programming/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service01/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service02/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service03/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service04/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service05/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service12/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service129/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service17/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service19/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_service20/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_sys_data_pool/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_tc_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/pus_tm_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/pus_services/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3/service_libraries/serialize/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito3 \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/asw/dataclasses/CDEvAction/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/asw/dataclasses/CDTCHandler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/asw/dataclasses/CDTCMemDescriptor/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/asw/edroom_glue/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/device_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_adc_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_display_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_gss/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_hw_timecode_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_sc_channel_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_uah_drone_cinematics/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/emu_watchdog_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/freertos_osswr/Source \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/obt_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/tc_queue_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/tc_rate_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/llsw/tmtc_dyn_mem/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/ccsds_pus/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/crc/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/drone_flight_pid_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/edroomsl/edroombp/src/freertossapi \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/edroomsl/edroomsl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/edroomsl/edroomsl_types/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/emu_tc_programming/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_service01/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_service05/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_service129/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_sys_data_pool/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_tc_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/pus_tm_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/pus_services/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug/service_libraries/serialize/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/Debug \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/components/ccbkgtcexec/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/components/ccdronemng/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/components/cchk_fdirmng/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/components/cctcmanager/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/components/uah_asw/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/dataclasses/CDEvAction/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/dataclasses/CDTCHandler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/dataclasses/CDTCMemDescriptor/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/asw/edroom_glue/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/device_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_adc_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_display_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_gss/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_hw_timecode_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_sc_channel_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_uah_drone_cinematics/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/emu_watchdog_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/freertos_osswr/Source \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/obt_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/tc_queue_drv/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/tc_rate_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/llsw/tmtc_dyn_mem/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/ccsds_pus/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/crc/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/drone_flight_pid_ctrl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/edroomsl/edroombp/src/freertossapi \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/edroomsl/edroomsl/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/edroomsl/edroomsl_types/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/emu_tc_programming/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service01/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service02/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service03/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service04/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service05/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service12/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service129/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service17/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service19/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_service20/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_sys_data_pool/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_tc_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/pus_tm_handler/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/pus_services/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4/service_libraries/serialize/src \
DJF/ITs/it_asw_ccdronemng_freertos_hito4 \
DJF/UTs/EDROOModel/UT_CCDroneMng/ClasesActor \
DJF/UTs/ut_ccdronemng_freertos/asw/components/ccdronemng/src \
DJF/UTs/ut_ccdronemng_freertos/asw/components/ccdronemngtester/src \
DJF/UTs/ut_ccdronemng_freertos/asw/components/ut_ccdronemng/src \
DJF/UTs/ut_ccdronemng_freertos/asw/dataclasses/CDEvAction/src \
DJF/UTs/ut_ccdronemng_freertos/asw/dataclasses/CDTCHandler/src \
DJF/UTs/ut_ccdronemng_freertos/asw/dataclasses/CDTCMemDescriptor/src \
DJF/UTs/ut_ccdronemng_freertos/asw/edroom_glue/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/device_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/emu_adc_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/emu_hw_timecode_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/emu_sc_channel_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/emu_watchdog_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/freertos_osswr/Source \
DJF/UTs/ut_ccdronemng_freertos/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/MemMang \
DJF/UTs/ut_ccdronemng_freertos/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix \
DJF/UTs/ut_ccdronemng_freertos/llsw/freertos_osswr/Source/portable/ThirdParty/GCC/Posix/utils \
DJF/UTs/ut_ccdronemng_freertos/llsw/obt_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/tc_queue_drv/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/tc_rate_ctrl/src \
DJF/UTs/ut_ccdronemng_freertos/llsw/tmtc_dyn_mem/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/ccsds_pus/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/crc/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/edroomsl/edroombp/src/freertossapi \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/edroomsl/edroomsl/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/edroomsl/edroomsl_types/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/pus_service01/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/pus_service129/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/pus_sys_data_pool/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/pus_tc_handler/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/pus_tm_handler/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/pus_services/src \
DJF/UTs/ut_ccdronemng_freertos/service_libraries/serialize/src \
DJF/UTs/ut_ccdronemng_freertos \

